import Header from "@/components/layouts/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { GlobalProvider } from "./GlobalProvider";
import Providers from "@/components/Providers";
import Footer from "@/components/layouts/Footer";
import Navbar from "@/components/layouts/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#F5F5F3]">
        <Providers>
          <GlobalProvider>
            <Header />
            {children}
            <Footer />
          </GlobalProvider>
        </Providers>
      </body>
    </html>
  );
}
